# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mesh_v1_pb2 as mesh__v1__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mesh_v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EdgeMeshServiceStub(object):
    """*
    BioGraph P2P Exchange Service
    Aligned with Indian Patent No. 202541127477
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncPeerEmbeddings = channel.unary_unary(
                '/zerocloud.edge.v1.EdgeMeshService/SyncPeerEmbeddings',
                request_serializer=mesh__v1__pb2.EmbeddingStream.SerializeToString,
                response_deserializer=mesh__v1__pb2.AuditAcknowledgment.FromString,
                _registered_method=True)


class EdgeMeshServiceServicer(object):
    """*
    BioGraph P2P Exchange Service
    Aligned with Indian Patent No. 202541127477
    """

    def SyncPeerEmbeddings(self, request, context):
        """Exchange quantized embeddings between peer nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeMeshServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncPeerEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncPeerEmbeddings,
                    request_deserializer=mesh__v1__pb2.EmbeddingStream.FromString,
                    response_serializer=mesh__v1__pb2.AuditAcknowledgment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zerocloud.edge.v1.EdgeMeshService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zerocloud.edge.v1.EdgeMeshService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EdgeMeshService(object):
    """*
    BioGraph P2P Exchange Service
    Aligned with Indian Patent No. 202541127477
    """

    @staticmethod
    def SyncPeerEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zerocloud.edge.v1.EdgeMeshService/SyncPeerEmbeddings',
            mesh__v1__pb2.EmbeddingStream.SerializeToString,
            mesh__v1__pb2.AuditAcknowledgment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
